services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: phi
      POSTGRES_PASSWORD: Adminpaco
      POSTGRES_DB: phi_dev
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ACCESS_KEY: pacoruan
      MINIO_SECRET_KEY: SigepAdmin
    volumes:
      - minio-data:/data

volumes:
  minio-data:
